add code
superazbuka/HashMap pull request #1
Opened 2019-03-05 19:33 UTC by superazbuka

2019-03-05 19:37 UTC, superazbuka commented
Ссылка на submit https://official.contest.yandex.ru/contest/11654/run-report/19465833/

2019-03-18 09:37 UTC, sartuhin requested changes

2019-03-18 09:37 UTC, sartuhin commented on hash_map.h
> +	size_t _size;
зачем _size начинается с _?

2019-03-18 09:37 UTC, sartuhin commented on hash_map.h
> +	size_t get_pos(const KeyType &key) const/*{{{*/
/*{{{*/ - что это?

2019-03-18 09:37 UTC, sartuhin commented on hash_map.h
> +		for (sub_iterator j = table[row].begin(); j != table[row].end(); ++j)
если оборачивать однострочные ифы и форы в {} код становится читаемым, правда это работает лучше в случае когда { идет на той же строчке что и иф, в вашем случае можно оставить так

2019-03-18 09:37 UTC, sartuhin commented on hash_map.h
> +		, table(1ul)
где то 1 где то 1ul

2019-03-18 11:13 UTC, closed without merging