Сахабиев Асхат 181-2 3 контест задача A
superazbuka/HashMap pull request #2
Opened 2019-03-18 11:15 UTC by superazbuka

_size потому-что есть функция size()

2019-03-18 11:16 UTC, superazbuka commented
/*{{{*/ это было foldmethod=marker в vim

2019-03-18 14:13 UTC, sartuhin requested changes

2019-03-18 14:13 UTC, sartuhin commented on hash_map.h
> +	size_t _size;
Стиль именования переменных должен быть один.
Нужно либо переименовать переменную, либо выбирать другой стиль именования для всех.
Подчеркивание в начала имен уже почти никто не использует.

2019-03-18 19:08 UTC, superazbuka commented on hash_map.h
> +	size_t _size;
я поменял на другое название.

2019-03-19 11:02 UTC, sartuhin approved these changes

2019-03-19 11:02 UTC, merged